### 1. Creating Arrays from Existing Data


* numpy.array(object, dtype=None)



* Creates an array from a list, tuple, or another array.



In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)


[1 2 3 4]


* numpy.asarray(a, dtype=None)



* Similar to np.array, but does not copy the array if it is already a NumPy array.



In [2]:
lst = [1, 2, 3]
arr = np.asarray(lst)
print(arr)

[1 2 3]


* numpy.copy(a)


* Returns a new copy of the array.



In [3]:
arr = np.array([1, 2, 3])
new_arr = np.copy(arr)
print(new_arr)


[1 2 3]


### 2. Creating Arrays with Placeholders (Zeros, Ones, Empty)


* numpy.zeros(shape, dtype=float)



* Creates an array filled with zeros.



In [4]:
arr = np.zeros((3, 3))
print(arr)  # 2x3 matrix of zeros

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


* numpy.ones(shape, dtype=float)



* Creates an array filled with ones.



In [5]:
arr = np.ones((3, 3))
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


* numpy.full(shape, fill_value, dtype=None)



* Creates an array filled with a specified value.



In [6]:
arr = np.full((2, 2), 5) 
print(arr) # 2x2 array filled with 7


[[5 5]
 [5 5]]


* numpy.empty(shape, dtype=float)



* Creates an uninitialized array (values may be random).



In [7]:
arr = np.empty((2, 2),dtype=int)
print(arr)

[[  615199866  -625625904]
 [-1947629104   218754105]]


### 3. Creating Identity and Diagonal Matrices


* numpy.eye(N, M=None, k=0, dtype=float)



* Creates an identity matrix or a diagonal matrix.



In [8]:
arr = np.eye(1,4)
print(arr)  # 3x3 identity matrix

[[1. 0. 0. 0.]]


* numpy.identity(n, dtype=float)



* Creates an identity matrix of size n x n.



In [9]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


* numpy.diag(v, k=0)



* Creates a diagonal matrix from a given array.



In [10]:
arr = np.diag([1, 2, 3, 4],k=1)
print(arr)  # Diagonal matrix with 1, 2, 3


[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


### 4. Creating Arrays with Ranges and Intervals


* numpy.arange(start, stop, step, dtype=None)



* Creates an array with evenly spaced values (similar to Python’s range).



In [11]:
arr = np.arange(1, 10,3)
print(arr)  # [1, 3, 5, 7, 9]


[1 4 7]


* numpy.linspace(start, stop, num=50, endpoint=True, dtype=None)



* Creates an array with num evenly spaced values between start and stop.



In [12]:
arr = np.linspace(0, 10, 5, endpoint=False)
print(arr)  # [0, 2.5, 5, 7.5, 10]


[0. 2. 4. 6. 8.]


* numpy.logspace(start, stop, num=50, base=10.0, dtype=None)



* Similar to linspace, but spaced logarithmically.



In [13]:
arr = np.logspace(1, 4, 4,base=2)
print(arr)

[ 2.  4.  8. 16.]


### 5. Creating Randomized Arrays


* numpy.random.rand(d0, d1, ..., dn)



* Creates an array of shape (d0, d1, ..., dn) with random values in the range [0, 1).



In [14]:
arr = np.random.rand(3,4)
print(arr)

[[0.13339229 0.31527257 0.06219612 0.44514127]
 [0.72073083 0.03559257 0.88462346 0.62910185]
 [0.18027904 0.2986014  0.94208373 0.84501073]]


* numpy.random.randint(low, high, size, dtype=int)



* Generates an array of random integers.



In [15]:
arr = np.random.randint(1, 10, (3, 3))
print(arr)

[[5 2 4]
 [8 7 8]
 [7 7 8]]


* numpy.random.randn(d0, d1, ..., dn)



* Returns a sample from the standard normal distribution.



In [16]:
arr = np.random.randn(3, 3)
print(arr)

[[-0.17679168  0.47028454 -1.49724412]
 [-0.07448216 -1.04973889  0.08274157]
 [-1.11032144 -1.56808199 -0.12094236]]


* numpy.random.choice(a, size, replace=True, p=None)



* Generates a random sample from a given 1D array.



In [17]:
arr = np.random.choice([10, 20, 30], size=(2,5))
print(arr)

[[30 10 10 30 30]
 [30 10 10 10 20]]
