# NumPy String Functions
This notebook explores various NumPy string functions in detail.

## 1. Changing Case

### `char.upper()` - Converts to uppercase

In [3]:
import numpy as np
arr = np.array(['hello', 'world'])
np.char.upper(arr)

array(['HELLO', 'WORLD'], dtype='<U5')

### `char.lower()` - Converts to lowercase

In [4]:
np.char.lower(['PYTHON', 'NUMPY'])

array(['python', 'numpy'], dtype='<U6')

### `char.title()` - Converts to title case

In [5]:
np.char.title(['hello world', 'python numpy'])

array(['Hello World', 'Python Numpy'], dtype='<U12')

## 2. String Concatenation

### `char.add()` - Concatenates two arrays element-wise

In [6]:
arr1 = np.array(['Hello', 'NumPy'])
arr2 = np.array([' World', ' Library'])
np.char.add(arr1, arr2)

array(['Hello World', 'NumPy Library'], dtype='<U13')

### `char.multiply()` - Repeats a string multiple times

In [7]:
np.char.multiply('NumPy ', 3)

array('NumPy NumPy NumPy ', dtype='<U18')

## 3. String Splitting and Joining

### `char.split()` - Splits each string at spaces

In [8]:
np.char.split(['Hello World', 'Python,NumPy'], sep=' ')

array([list(['Hello', 'World']), list(['Python,NumPy'])], dtype=object)

### `char.splitlines()` - Splits at newline characters

In [9]:
np.char.splitlines(['Hello\nWorld', 'NumPy\nPython'])

array([list(['Hello', 'World']), list(['NumPy', 'Python'])], dtype=object)

### `char.join()` - Joins elements using a separator

In [10]:
arr = np.array(['abc', 'xyz'])
np.char.join('-', arr)

array(['a-b-c', 'x-y-z'], dtype='<U5')

## 4. String Padding and Trimming

### `char.center()` - Centers the string within a width

In [11]:
np.char.center('NumPy', 10, fillchar='-')

array('--NumPy---', dtype='<U10')

### `char.strip()` - Removes leading and trailing spaces

In [12]:
np.char.strip(['  hello  ', ' numpy  '])

array(['hello', 'numpy'], dtype='<U9')

## 5. Searching and Replacing

### `char.find()` - Finds the index of a substring

In [13]:
np.char.find(['Hello World', 'Python NumPy'], 'o')

array([4, 4])

### `char.replace()` - Replaces occurrences of a substring

In [14]:
np.char.replace(['Hello World', 'Python NumPy'], 'o', '0')

array(['Hell0 W0rld', 'Pyth0n NumPy'], dtype='<U12')

## 6. String Comparison

### `char.equal()` - Checks if two arrays are equal element-wise

In [15]:
np.char.equal(['apple', 'banana'], ['apple', 'orange'])

array([ True, False])

### `char.greater()` & `char.less()` - Lexicographical comparison

In [16]:
np.char.greater(['apple', 'banana'], ['apple', 'orange'])

array([False, False])

## 7. Checking String Properties

### `char.isnumeric()` - Checks if all characters are numeric

In [17]:
np.char.isnumeric(['123', 'abc', '456'])

array([ True, False,  True])

### `char.isalpha()` - Checks if all characters are alphabetic

In [18]:
np.char.isalpha(['Hello', '123', 'World'])

array([ True, False,  True])

## 8. Encoding and Decoding

### `char.encode()` & `char.decode()` - Encodes and decodes strings

In [19]:
encoded = np.char.encode(['hello', 'numpy'], encoding='utf-8')
encoded

array([b'hello', b'numpy'], dtype='|S5')

In [20]:
decoded = np.char.decode(encoded, encoding='utf-8')
decoded

array(['hello', 'numpy'], dtype='<U5')

## Conclusion
NumPy’s `char` module provides a powerful way to manipulate string arrays efficiently.