# NumPy Mathematical Functions

This notebook covers various mathematical functions in NumPy, including trigonometric, exponential, logarithmic, power, rounding, absolute, statistical, and special functions.

## 1. Trigonometric Functions
These functions operate on angles and are useful in geometric and scientific computations.

In [1]:
import numpy as np

angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2])

print(np.sin(angles))  # Sine
print(np.cos(angles))  # Cosine
print(np.tan(angles))  # Tangent

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]
[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  5.44374645e+15]


### Inverse Trigonometric Functions
These return angles in radians.

In [2]:
values = np.array([0, 0.5, 1])

print(np.arcsin(values))  # Inverse Sine
print(np.arccos(values))  # Inverse Cosine
print(np.arctan(values))  # Inverse Tangent

[0.         0.52359878 1.57079633]
[1.57079633 1.04719755 0.        ]
[0.         0.46364761 0.78539816]


### Hyperbolic Functions

In [3]:
x = np.array([0, 1, -1])

print(np.sinh(x))  # Hyperbolic Sine
print(np.cosh(x))  # Hyperbolic Cosine
print(np.tanh(x))  # Hyperbolic Tangent

[ 0.          1.17520119 -1.17520119]
[1.         1.54308063 1.54308063]
[ 0.          0.76159416 -0.76159416]


## 2. Exponential and Logarithmic Functions
These functions are useful for scientific and engineering applications.

In [4]:
x = np.array([0, 1, 2])

print(np.exp(x))      # e^x
print(np.expm1(x))    # e^x - 1
print(np.exp2(x))     # 2^x

[1.         2.71828183 7.3890561 ]
[0.         1.71828183 6.3890561 ]
[1. 2. 4.]


In [5]:
x = np.array([1, np.e, 10])

print(np.log(x))      # Natural Log (base e)
print(np.log10(x))    # Log base 10
print(np.log2(x))     # Log base 2
print(np.log1p(x))    # log(1 + x)

[0.         1.         2.30258509]
[0.         0.43429448 1.        ]
[0.         1.44269504 3.32192809]
[0.69314718 1.31326169 2.39789527]


## 3. Power and Root Functions

In [6]:
x = np.array([1, 4, 9, 16])

print(np.sqrt(x))     # Square Root
print(np.cbrt(x))     # Cube Root
print(np.square(x))   # Square (x^2)
print(np.power(x, 3)) # x^3

[1. 2. 3. 4.]
[1.         1.58740105 2.08008382 2.5198421 ]
[  1  16  81 256]
[   1   64  729 4096]


## 4. Rounding Functions

In [7]:
x = np.array([1.4, 1.6, 2.5, -1.5])

print(np.round(x))    # Round to nearest integer
print(np.floor(x))    # Round down
print(np.ceil(x))     # Round up
print(np.trunc(x))    # Truncate decimal part

[ 1.  2.  2. -2.]
[ 1.  1.  2. -2.]
[ 2.  2.  3. -1.]
[ 1.  1.  2. -1.]


## 5. Absolute and Sign Functions

In [8]:
x = np.array([-1, -2, 0, 3, 4])

print(np.abs(x))      # Absolute value
print(np.sign(x))     # Sign of numbers (-1, 0, or 1)

[1 2 0 3 4]
[-1 -1  0  1  1]


## 6. Statistical Functions
These functions help in data analysis.

In [9]:
x = np.array([1, 2, 3, 4, 5])

print(np.min(x))      # Minimum
print(np.max(x))      # Maximum
print(np.mean(x))     # Mean (Average)
print(np.median(x))   # Median
print(np.std(x))      # Standard Deviation
print(np.var(x))      # Variance

1
5
3.0
3.0
1.4142135623730951
2.0


## 7. Special Functions

### GCD and LCM

In [10]:
a = 15
b = 20

print(np.gcd(a, b))   # Greatest Common Divisor
print(np.lcm(a, b))   # Least Common Multiple

5
60


### Factorial and Gamma Function

In [11]:
x = np.array([3, 4, 5])

print(np.math.factorial(5))   # Factorial (only for scalars)
print(np.prod(x))             # Product of array elements
print(np.cumprod(x))          # Cumulative product

120
60
[ 3 12 60]


## Conclusion
NumPy provides a wide range of mathematical functions that allow efficient numerical computations on arrays. This notebook covered the most commonly used functions.