# **NumPy Arithmetic Operations in Depth**

NumPy provides a set of arithmetic operations that allow efficient mathematical computations on arrays. These operations are vectorized, meaning they are performed element-wise, making them much faster than traditional Python loops.

## **1. Basic Arithmetic Operations**
NumPy supports element-wise addition, subtraction, multiplication, and division.

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
print(a + b)

# Subtraction
print(a - b)

# Multiplication
print(a * b)

# Division
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## **2. Scalar Arithmetic Operations**
You can perform arithmetic operations between a NumPy array and a scalar.

In [2]:
a = np.array([1, 2, 3])

# Addition with a scalar
print(a + 10)

# Multiplication with a scalar
print(a * 3)

# Division with a scalar
print(a / 2)

# Exponentiation
print(a ** 2)

[11 12 13]
[3 6 9]
[0.5 1.  1.5]
[1 4 9]


## **3. Unary Operations (on a single array)**

In [3]:
a = np.array([-1, 2, -3, 4])

# Absolute values
print(np.abs(a))

# Square root
print(np.sqrt(np.array([4, 9, 16])))

# Exponentiation (e^x)
print(np.exp(np.array([1, 2, 3])))

# Logarithm (natural log)
print(np.log(np.array([1, np.e, np.e**2])))

[1 2 3 4]
[2. 3. 4.]
[ 2.71828183  7.3890561  20.08553692]
[0. 1. 2.]


## **4. Broadcasting in Arithmetic Operations**

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

# Broadcasting: Adding b to each row of a
print(a + b)

[[11 22 33]
 [14 25 36]]


## **5. Aggregation Functions in NumPy**

In [5]:
a = np.array([1, 2, 3, 4, 5])

# Sum of elements
print(np.sum(a))

# Mean (average)
print(np.mean(a))

# Standard deviation
print(np.std(a))

# Minimum and Maximum
print(np.min(a), np.max(a))

# Cumulative sum
print(np.cumsum(a))

15
3.0
1.4142135623730951
1 5
[ 1  3  6 10 15]


## **6. Element-wise Comparison Operations**

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 3, 5])

# Element-wise comparison
print(a == b)

# Greater than
print(a > b)

# Logical operations
print(np.any(a > b))
print(np.all(a >= b))

[False  True  True False]
[False False False False]
False
False


## **7. Matrix Multiplication vs. Element-wise Multiplication**

In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

# Element-wise multiplication
print(A * B)

# Matrix multiplication
print(A @ B)  # OR np.dot(A, B)

[[ 2  0]
 [ 3 12]]
[[ 4  6]
 [10 12]]


## **8. Handling NaN and Infinite Values**

In [8]:
a = np.array([1, np.nan, 2, np.inf])

# Check for NaN
print(np.isnan(a))

# Check for Inf
print(np.isinf(a))

# Replace NaN with a value
a[np.isnan(a)] = 0
print(a)

[False  True False False]
[False False False  True]
[ 1.  0.  2. inf]


## **9. Modulo and Floor Division**

In [9]:
a = np.array([7, 15, 22])

# Modulo (remainder)
print(a % 5)

# Floor division
print(a // 5)

[2 0 2]
[1 3 4]


## **10. Rounding Functions**

In [10]:
a = np.array([1.23, 4.56, 7.89])

# Round to nearest integer
print(np.round(a))

# Floor (round down)
print(np.floor(a))

# Ceil (round up)
print(np.ceil(a))

[1. 5. 8.]
[1. 4. 7.]
[2. 5. 8.]


### **Conclusion**
NumPy provides a powerful and efficient way to perform arithmetic operations on arrays. With features like broadcasting, vectorized operations, and aggregation functions, it is the backbone of numerical computing in Python.