## 1. LU Decomposition (Lower-Upper Decomposition)


LU decomposition expresses a square matrix 
𝐴 as:

𝐴=𝐿U


where:

𝐿
 is a lower triangular matrix (all elements above the diagonal are 0).

𝑈
is an upper triangular matrix (all elements below the diagonal are 0).

Use Cases:

Efficiently solving linear equations 
𝐴𝑥=𝑏 (better than Gaussian elimination).

Computing matrix inverses and determinants.

In [1]:
import numpy as np
from scipy.linalg import lu

A = np.array([[2, 3, 1], 
              [4, 7, 5], 
              [6, 18, 9]])

P, L, U = lu(A)  # P: Permutation matrix, L: Lower, U: Upper

print("L:\n", L)
print("U:\n", U)
print("P:\n", P)  # Ensures stability (partial pivoting)


L:
 [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.6        1.        ]]
U:
 [[ 6.  18.   9. ]
 [ 0.  -5.  -1. ]
 [ 0.   0.  -1.4]]
P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
