The ndarray is the core NumPy object, supporting operations like slicing, reshaping, and broadcasting.

Creating Arrays

In [1]:
import numpy as np

# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D Array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# 3D Array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr1.ndim)  # 1D
print(arr2.ndim)  # 2D
print(arr3.ndim)  # 3D


1
2
3


Creating Special Arrays

In [5]:
# Array of zeros
zeros = np.zeros((3, 3))

# Array of ones
ones = np.ones((2, 4))

# Identity Matrix
identity = np.eye(3)

# Random numbers
random_arr = np.random.rand(2, 3)

# Range of numbers
range_arr = np.arange(1, 10, 2)  # [1, 3, 5, 7, 9]

print(zeros)
print(ones)
print(identity)
print(random_arr)
print(range_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.10287252 0.60595341 0.05194971]
 [0.39904073 0.17763682 0.4848266 ]]
[1 3 5 7 9]
