## 1. Sorting in NumPy


NumPy provides several functions to sort arrays efficiently.



#### 1.1 numpy.sort()

* Returns a sorted copy of an array.

* Works along a specified axis.

* Uses QuickSort, MergeSort, or HeapSort algorithms.

In [2]:
import numpy as np

arr = np.array([3, 1, 2, 4])
sorted_arr = np.sort(arr)
print(sorted_arr)  # Output: [1 2 3 4]


[1 2 3 4]


Sorting along different axes:

In [3]:
arr2D = np.array([[3, 2, 1], [6, 5, 4]])
print(np.sort(arr2D, axis=0))  # Sort columns
print(np.sort(arr2D, axis=1))  # Sort rows


[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]


#### 1.2 numpy.argsort()


* Returns the indices that would sort an array.

In [4]:
arr = np.array([3, 1, 2, 4])
indices = np.argsort(arr)
print(indices)  # Output: [1 2 0 3]

[1 2 0 3]


### 2. Searching in NumPy

NumPy provides functions to search for elements efficiently.

#### 2.1 numpy.where()

* Returns the indices of elements that satisfy a condition.

In [ ]:
arr = np.array([10, 20, 30, 40])
result = np.where(arr > 20)
print(result)  

(array([2, 3], dtype=int64),)


For multiple conditions:

In [ ]:
arr = np.array([10, 20, 30, 40])
result = np.where((arr > 10) & (arr < 40))
print(result)

(array([1, 2], dtype=int64),)


#### 2.2 numpy.searchsorted()


Finds the indices where elements should be inserted to maintain order.

In [14]:
arr = np.array([1, 3, 5, 7])
pos = np.searchsorted(arr, 0)
print(pos)  

0


#### 2.3 numpy.nonzero()


* Returns indices of non-zero elements.

In [8]:
arr = np.array([0, 1, 0, 2, 3])
result = np.nonzero(arr)
print(result)  # Output: (array([1, 3, 4]),)


(array([1, 3, 4], dtype=int64),)


### 3. Counting Elements in NumPy


NumPy provides functions to count occurrences of elements.



#### 3.1 numpy.count_nonzero()


* Counts the number of non-zero elements.


In [9]:
arr = np.array([0, 1, 0, 2, 3])
count = np.count_nonzero(arr)
print(count)  # Output: 3


3


For multi-dimensional arrays:

In [10]:
arr2D = np.array([[0, 1, 2], [3, 0, 4]])
count = np.count_nonzero(arr2D, axis=0)  # Count along columns
print(count)  # Output: [1 1 2]


[1 1 2]


#### 3.2 numpy.unique()

* Returns unique values in an array.

* Can also return counts of unique values.

In [11]:
arr = np.array([1, 2, 2, 3, 3, 3])
unique_values, counts = np.unique(arr, return_counts=True)
print(unique_values)  # Output: [1 2 3]
print(counts)         # Output: [1 2 3]


[1 2 3]
[1 2 3]


### Summary

|      Function	|      Purpose| 
|-------------- | --------------|    
|      numpy.sort()	|      Sorts an array|      
|      numpy.argsort()	|      Returns indices of sorted elements|      
|      numpy.where()	|      Finds indices based on a condition|      
|      numpy.searchsorted()	|      Finds where an element should be inserted in a sorted array|      
|      numpy.nonzero()	|      Finds indices of non-zero elements|      
|      numpy.count_nonzero()	|      Counts non-zero elements|      
|      numpy.unique()	|      Finds unique elements and their counts|      