The NumPy Matrix Library is a powerful tool in Python for handling multidimensional arrays, linear algebra, and matrix operations. NumPy provides two primary data structures for working with matrices:

1.numpy.array (Recommended for General Use)

2.numpy.matrix (Deprecated, Use numpy.array Instead)

### 1. Creating Matrices in NumPy
Using numpy.array() (Preferred)

In [2]:
import numpy as np

A = np.array([[1, 2], [3, 4]])  # 2x2 matrix
print(A)

[[1 2]
 [3 4]]


🔹 numpy.array is flexible and supports element-wise operations.

Using numpy.matrix() (Deprecated)

In [ ]:
B = np.matrix([[1, 2],[3, 4]])
print(B)

[[1 2]
 [3 4]]


🔹 numpy.matrix enforces strict matrix multiplication rules but is now discouraged.

### 2. Matrix Operations
Addition & Subtraction

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B  # Element-wise addition
D = A - B  # Element-wise subtraction
print(C)
print(D)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


Matrix Multiplication
* Element-wise Multiplication (*):

In [5]:
C = A * B  # Multiplies element-wise
print(C)


[[ 5 12]
 [21 32]]


* Dot Product (np.dot() or @):

In [6]:
D = np.dot(A, B)  # Matrix multiplication
E = A @ B  # Equivalent to np.dot(A, B)
print(D)
print(E)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Transpose (.T)


In [ ]:
A_T = A.T
print(A_T)

[[1 3]
 [2 4]]


Inverse (np.linalg.inv())

In [8]:
A_inv = np.linalg.inv(A)  # Inverse of A
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


Determinant (np.linalg.det())

In [9]:
det_A = np.linalg.det(A)
print(det_A)

-2.0000000000000004


Eigenvalues & Eigenvectors

In [10]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### 3. Special Matrices

Identity Matrix (np.eye())

In [11]:
I = np.eye(3)  # 3x3 identity matrix
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Zero Matrix (np.zeros())

In [12]:
Z = np.zeros((3, 3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Ones Matrix (np.ones())

In [13]:
O = np.ones((3, 3))
print(O)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Diagonal Matrix (np.diag())

In [14]:
D = np.diag([1, 2, 3])
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


### 4. Solving Linear Equations

To solve Ax = B, use np.linalg.solve(A, B).

In [ ]:
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])
x = np.linalg.solve(A, B)
print(x)

[2. 3.]


### 5. Singular Value Decomposition (SVD)

In [ ]:
U, S, V = np.linalg.svd(A)
print(U)
print(S)
print(V) 

[[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
[3.61803399 1.38196601]
[[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]


### 6. Pseudo-Inverse (np.linalg.pinv())
For non-invertible matrices:

In [17]:
A_pinv = np.linalg.pinv(A)
print(A_pinv)

[[ 0.4 -0.2]
 [-0.2  0.6]]


### 7. Broadcasting in Matrix Operations
NumPy automatically expands smaller arrays to match dimensions.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([1, 2])  

C = A + B  # Broadcasts B to match A
print(C)

[[2 4]
 [4 6]]


### 8. Performance Optimization with NumPy
* Use vectorized operations instead of loops.

* Use np.dot() instead of for loops for matrix multiplication.

* Use NumPy's built-in functions for linear algebra instead of custom implementations.

### Conclusion
* umpy.array is recommended over numpy.matrix.

* Use NumPy’s linear algebra functions for efficient matrix computations.

* Broadcasting makes array operations flexible.

* NumPy optimizes performance with vectorized operations.