### 1. Basics of Linear Algebra in NumPy
NumPy’s linalg module provides efficient methods for common linear algebra operations. It is built on top of optimized LAPACK and BLAS routines.

To use it:

In [5]:
import numpy as np

### 2. Vectors and Matrices
NumPy represents vectors as 1D arrays and matrices as 2D arrays.

* Vector Example:

In [6]:
v = np.array([3, 4, 5])  # 1D array (vector)

* Matrix Example:

In [7]:
A = np.array([[1, 2], [3, 4]])  # 2D array (matrix)

### 3. Matrix Operations
3.1 Matrix Transposition

In [ ]:
A = np.array([[1, 2], [3, 4]])
A_T = A.T
print(A_T)

[[1 3]
 [2 4]]


3.2 Matrix Addition & Subtraction

In [9]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B  # Matrix addition
D = A - B  # Matrix subtraction


3.3 Matrix Multiplication

Element-wise Multiplication (* operator)

In [10]:
A * B  # Multiplies element-wise

array([[ 5, 12],
       [21, 32]])

Dot Product (np.dot() or @ operator)

In [ ]:
dot_product = np.dot(A, B)  # Matrix multiplication
dot_product_alt = A @ B     # Equivalent to np.dot()

### 4. Determinant of a Matrix
The determinant of a matrix is useful in solving linear equations, finding inverses, and more.

In [12]:
A = np.array([[1, 2], [3, 4]])
det_A = np.linalg.det(A)
print(det_A)


-2.0000000000000004


### 5. Inverse of a Matrix
The inverse of a square matrix A  is denoted as A^-1 , where:

   *     AA^-1=I
   

In [13]:
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print(A_inv)


[[-2.   1. ]
 [ 1.5 -0.5]]


Note: A matrix must be non-singular (i.e., determinant ≠ 0) to have an inverse.



### 6. Solving Linear Systems

Solving Ax=b for x:


In [ ]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print(x)

[2. 3.]


This avoids explicit inversion (which can be numerically unstable).



### 7. Eigenvalues & Eigenvectors

For a matrix A:
   *   Av=𝜆v


where:

𝜆
 are eigenvalues

𝑣
are eigenvectors

In [ ]:
A = np.array([[4, -2], [1, 1]])
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors:", eigvecs)

Eigenvalues: [3. 2.]
Eigenvectors: [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


8. Singular Value Decomposition (SVD)

SVD decomposes a matrix 𝐴 into:
  * A = USV^2

In [16]:
A = np.array([[3, 1], [1, 2], [2, 2]])
U, S, Vt = np.linalg.svd(A)
print("U:\n", U)
print("S:\n", S)
print("Vt:\n", Vt)

U:
 [[-0.65572913  0.69363565 -0.2981424 ]
 [-0.4394979  -0.67177827 -0.59628479]
 [-0.61388997 -0.25996835  0.74535599]]
S:
 [4.56516931 1.46943158]
Vt:
 [[-0.79612934 -0.60512649]
 [ 0.60512649 -0.79612934]]


SVD is widely used in PCA, dimensionality reduction, and image compression.



### 9. Norms of a Vector or Matrix
Norms measure vector/matrix magnitude.

* L2 Norm (Euclidean norm)

In [17]:
v = np.array([3, 4])
norm_v = np.linalg.norm(v)  # sqrt(3^2 + 4^2) = 5


* L1 Norm (Manhattan norm)

In [18]:
norm_v1 = np.linalg.norm(v, 1)  # |3| + |4| = 7

* Frobenius Norm (Matrix Norm)

In [19]:
A = np.array([[1, 2], [3, 4]])
frobenius_norm = np.linalg.norm(A, 'fro')

### 10. QR Decomposition
QR decomposition expresses a matrix as:

  * A = QR

where 𝑄 is orthogonal and 𝑅 is upper triangular.

In [20]:
A = np.array([[1, 2], [3, 4]])
Q, R = np.linalg.qr(A)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R:
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


### 11. Cholesky Decomposition (For Positive-Definite Matrices)
If 𝐴 is symmetric and positive definite:
  * A = LL^T

In [21]:
A = np.array([[4, 2], [2, 3]])
L = np.linalg.cholesky(A)
print("L:\n", L)


L:
 [[2.         0.        ]
 [1.         1.41421356]]


### 12. Moore-Penrose Pseudoinverse
For non-square matrices or singular matrices:

In [22]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A_pinv = np.linalg.pinv(A)
print(A_pinv)

[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


Applications of NumPy Linear Algebra
* Machine Learning (e.g., solving normal equations in linear regression)

* Data Science (e.g., PCA for dimensionality reduction)

* Computer Graphics (e.g., transformations using matrices)

* Physics & Engineering (e.g., solving equations in simulations)

* Image Processing (e.g., SVD for image compression)