## 1. Saving and Loading Arrays
#### 1.1 Binary File Format (.npy)
NumPy’s .npy format is optimized for storing single arrays in a binary format with metadata.

Saving an Array

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
np.save('array.npy', arr)

Loading an Array

In [20]:
loaded_arr = np.load('array.npy')
print(loaded_arr)

[[1 2 3]
 [4 5 6]]


 Advantages:

* Preserves data type and shape.

* Efficient storage and retrieval.

#### 1.2 Multiple Arrays (.npz format)
You can store multiple arrays in a single file using .npz.

Saving Multiple Arrays

In [21]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([[1, 2], [3, 4]])

np.savez('multiple_arrays.npz', first=arr1, second=arr2)


Loading Multiple Arrays

In [22]:
loaded = np.load('multiple_arrays.npz')
print(loaded['first'])  # Access first array
print(loaded['second']) # Access second array

[10 20 30]
[[1 2]
 [3 4]]


✅ Advantages:

* Stores multiple arrays in a compressed format.

* Uses dictionary-like key access.

## 2. Saving and Loading Text Files
NumPy also supports text-based I/O.

#### 2.1 Saving to a Text File (.txt, .csv)
Using savetxt()

In [23]:
np.savetxt('data.txt', arr, delimiter=',', fmt='%d')

* delimiter=',' → Specifies column separation.

* fmt='%d' → Controls the format (integer in this case).

Using tofile() (Raw Binary/Text)

In [24]:
arr.tofile('raw_data.bin')

#### 2.2 Loading from a Text File
Using loadtxt()

In [25]:
data = np.loadtxt('data.txt', delimiter=',', dtype=int)
print(data)


[[1 2 3]
 [4 5 6]]


Using fromfile()

In [26]:
raw_data = np.fromfile('raw_data.bin', dtype=np.int32)
print(raw_data)

[1 2 3 4 5 6]


✅ Use Cases:

* savetxt() and loadtxt() are human-readable.

* tofile() and fromfile() are faster but lack metadata.

## 3. Handling CSV Files
#### 3.1 Saving to CSV

In [27]:
np.savetxt('data.csv', arr, delimiter=',', fmt='%d', header='col1,col2,col3')

#### 3.2 Loading CSV

In [28]:
csv_data = np.loadtxt('data.csv', delimiter=',', skiprows=1, dtype=int)
print(csv_data)

[[1 2 3]
 [4 5 6]]


## 4. Handling Large Files
For large datasets, use memmap to avoid loading the full array into memory.

Using memmap for Large Data

In [29]:
large_arr = np.memmap('large_data.dat', dtype='float32', mode='w+', shape=(10000, 10000))
large_arr[:] = np.random.rand(10000, 10000)  # Assign values without full memory usage
del large_arr  # Flush changes to disk

# Load back
large_arr_loaded = np.memmap('large_data.dat', dtype='float32', mode='r', shape=(10000, 10000))
print(large_arr_loaded[0, :10])  # Access part of the array


[0.21231301 0.09442492 0.31180766 0.3660144  0.33762398 0.8815037
 0.47535494 0.7169954  0.30740893 0.16903509]


✅ Advantages:

* Handles large arrays without RAM overflow.

* Allows on-demand loading.

## 5. Pickle for Saving Any NumPy Object

In [30]:
import pickle

with open('array.pkl', 'wb') as f:
    pickle.dump(arr, f)

# Load
with open('array.pkl', 'rb') as f:
    arr_loaded = pickle.load(f)


✅ Use Case:

* Stores arbitrary Python objects beyond arrays.

#### Conclusion
|Method    |  	Format|	Supports Multiple Arrays|	Human Readable|	Metadata Preserved|
|----------|-----------|---------------------|--------------------|-------------------|
|.npy	  |      Binary	       | ❌	        |          ❌         |	✅|
|.npz	  |      Compressed Binary|	✅	   |           ❌	      |   ✅|
|savetxt()|	   Text (CSV/TXT)	|   ❌	   |             ✅	    |    ❌|
|loadtxt()|	   Text (CSV/TXT)|	❌	       |              ✅	    |       ❌|
|tofile()|	    Raw Binary	|    ❌	       |           ❌	        |     ❌|
|fromfile()	|   Raw Binary	|    ❌	       |           ❌	        |        ❌|
|memmap	|      Binary	|        ❌	       |            ❌	    |    ✅|
|pickle	 |     Binary	|        ✅	       |         ❌	        |    ✅|